"""Application-wide configuration constants."""

SERVER_ENDPOINT = "opc.tcp://0.0.0.0:4840/traffic-light/"
SERVER_NAME = "Smart Factory Traffic Light OPC UA Server"
NAMESPACE_URI = "urn:smart-factory:traffic-light"

RED_GPIO = 17
YELLOW_GPIO = 27
GREEN_GPIO = 23
TOUCH_GPIO = 5

DEFAULT_RED_DURATION = 8.0
DEFAULT_YELLOW_DURATION = 1.0
DEFAULT_GREEN_DURATION = 8.0
DEFAULT_GREEN_AFTER_TOUCH_DURATION = 4.0

GPIO_POLL_INTERVAL = 0.1
OPCUA_SYNC_INTERVAL = 0.2
